batch_type: folded
# larger batch size(CPU load increases), better performance. 
batch_size: 32
accum_grad: 8
# epoch: look over whole data once
max_epoch: 100
patience: none
# The initialization method for model parameters
# affects traning velocity and performance
init: xavier_uniform
# choose max acc in valid
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    # # of input
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model_conf:
    # multitask learning
    ctc_weight: 0.3
    lsm_weight: 0.1
    # label smoothing
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.001
# at the beginning, increase linearly. After that, it decrese sharply
scheduler: warmuplr #spectraAugmention
scheduler_conf:
    warmup_steps: 20000
    
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
